apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"my-nginx"},"name":"my-nginx","namespace":"tshoot-1"},"spec":{"ports":[{"name":"http","nodePort":30080,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"run":"another-app"},"type":"NodePort"}}
  creationTimestamp: "2021-12-21T16:42:16Z"
  labels:
    run: my-nginx
  name: my-nginx
  namespace: tshoot-1
  resourceVersion: "3254713"
  uid: 8fe0efd7-8205-4594-be65-eadb4097c060
spec:
  clusterIP: 10.111.35.157
  clusterIPs:
  - 10.111.35.157
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: another-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
