apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"my-nginx","namespace":"tshoot-1"},"spec":{"replicas":2,"selector":{"matchLabels":{"run":"my-nginx"}},"template":{"metadata":{"labels":{"run":"my-nginx"}},"spec":{"containers":[{"image":"ngix:latest","name":"nginx-latest","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"0.5","memory":"200Mi"},"requests":{"cpu":"0.25","memory":"100Mi"}}}]}}}}
  creationTimestamp: "2021-12-21T16:42:17Z"
  generation: 1
  name: my-nginx
  namespace: tshoot-1
  resourceVersion: "3254745"
  uid: 967263c3-c2ed-4ce6-9d2d-d12d3a0d25d8
  labels:
    run: another-app
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: another-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: another-app
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx-latest
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 250m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-12-21T16:42:20Z"
    lastUpdateTime: "2021-12-21T16:42:20Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-12-21T16:42:17Z"
    lastUpdateTime: "2021-12-21T16:42:22Z"
    message: ReplicaSet "my-nginx-7f455c4c8c" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
