apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cldinf-app
  namespace: cldinf-app
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: localstorage
  hostPath:
    path: /mnt/data