apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cldinf-app
  namespace: cldinf-app
spec:
  storageClassName: localstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi